name: Angular CD for DEV(Callable)

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID_NTU:
        required: true
      AWS_SECRET_ACCESS_KEY_NTU:
        required: true
      AWS_REGION_NTU:
        required: true
      DEV_S3_BUCKET_NAME:
        required: true
      DEV_CLOUDFRONT_DISTRIBUTION_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      

      - name: Download artifact from caller
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NTU }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NTU }}
          aws-region: ${{secrets.AWS_REGION_NTU}}

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Deploy to S3
        run: aws s3 sync dist/capstoneproject_group4_frontend/browser/ s3://${{ secrets.DEV_S3_BUCKET_NAME }} --delete

      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
